apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-api.fullname" . }}
  labels:
    {{- include "simple-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-api.selectorLabels" . | nindent 4 }}
---
## Redis
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
  {{- include "simple-api.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379