name: Release
on:
  push:
    tags:
      - v1.**
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get the tag name
        id: get_tag_name
        run: |
          # Extract tag name and remove "v" if present
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            "${{vars.BUILDKIT_IMAGE}}:${{ env.VERSION }}"
            "${{vars.BUILDKIT_IMAGE}}:latest"
